### PR TITLE
[master] Handle graceful shutdown.

### PR DESCRIPTION
**Pull request by hotpxl**
Handle graceful shutdown. When mahimahi closes stuff and the pipe is broken

### CODE REVIEW

**Comment by hotpxl** [comment]
When mahimahi shuts down, sending down the UDP socket will give unix error. Originally it will call std::terminate to shutdown the whole program. Now instead, we return Exit to the poller explicitly to let it shut down gracefully.

**Comment by keithw** [comment]
Thanks for the PR! In general I think we do want errors (e.g. from syscalls) to lead to an exception and a user-visible error message, so I am hesitant to quite take this in general. But, I also don't want students to get confused by seeing an (in this case benign) error message at the end of a "contest" experiment.

Question 1: Are you sure the exception you're seeing is coming from the sourdough sender, as opposed to the receiver? If so, it seems like the right fix might just be to make sure that when mahimahi is shutting down, it kills the ChildProcess (the sender) before it tears down the network devices underneath it.

My suspicion is that the error message might be coming from the sourdough receiver, which is outside the mahimahi container and might be harder to deal with in general. If it's coming from the receiver, the right answer might be a `--silent` command-line flag, and have run-contest.sh invoke it with that...

**Comment by hotpxl** [comment]
I'm 100% sure the error message came from this line. I separated log files for both application and run a comparison with & without this line.

Killing the child process sounds a better idea. Or more gracefully, send a SIGUSR or alike.

**Comment by keithw** [comment]
Okay, then this might be as simple as reordering the members of mahimahi's `PacketShell`, so the `EventLoop` (which holds the `ChildProcess`es) gets destroyed before the `TunDevice`. (Destroying a `ChildProcess` object sends a kill signal to the child process.)

https://github.com/ravinet/mahimahi/blob/master/src/packet/packetshell.hh

If you are able to get rid of the spurious error that way, I'd totally take a PR to mahimahi.

**Comment by hotpxl** [comment]
The source code I saw, `EventLoop` is already declared after `TunDevice`, meaning it will be constructed after `TunDevice` and destroyed before `TunDevice`.

**Comment by keithw** [comment]
In that case, why isn't the sender getting killed as soon as the trace runs out (before it has a chance to get an error from the missing TUN device)?

**Comment by hotpxl** [comment]
In this case, I found that
1. mahimahi has indeed sent SIGHUP to children upon exiting
2. sender does respond to SIGHUP by shutting down

but when you run sender, you don't run it directly. you wrap a `sh -c` around it. This `sh` intercepts the `SIGHUP`, exits itself and leaves `sender` as an orphan. It does not pass down the signal.

I guess "bash" pass down SIGHUP, but not "sh", which used to be a specific shell but is now really distro dependent.

**Comment by hotpxl** [comment]
Yes. Changing "sh" to "bash" on line 32 of `run-contest` will make sure that the sender receives the `SIGHUP` all the way from mahimahi. But then, I get another `unix_error` saying that

```
terminate called after throwing an instance of 'unix_error'
  what():  poll: Interrupted system call
```

~~Apparently I need to install a signal handler in `sender.cc` and somehow gracefully shuts down the poller. Does it offer a `shutdown` method or similar?~~
I overcame this by explicitly checking for `EINTR`.

**Comment by hotpxl** [comment]
See updated fix.

**Comment by hotpxl** [comment]
@keithw could you take a look at the new fix? i modified `run-contest` so it will pass down signals. i also modified `poller` to handle `EINTR` (which corresponds to a `SIGHUP` signal)

**Comment by keithw** [comment]
It looks good! I think we will apply this after the end of the contest. We'd be tempting fate by pushing a hotfix for a cosmetic issue in the middle of the assignment. :-)

**Pull request closed without merging**
